"""add zones table

Revision ID: cc86113c3682
Revises: 8ea9ab508dd8
Create Date: 2026-04-14 21:45:07.338662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc86113c3682'
down_revision: Union[str, Sequence[str], None] = '8ea9ab508dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('iid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('iid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    # ### end Alembic commands ###
